theme: jekyll-theme-slate
title: Welcome to the IVATO's publication page!
description: IVATO stands for Information Visualization, Algorithms,Theory and Optimization group, and is a lab at the Informatics Institute at the Federal University of Goiás, Brazil. 
